### PR TITLE
VYZN-499: vyzn customization changes

### PR DESCRIPTION
**Pull request by maurii90**

### CODE REVIEW

**Comment by rti-vyzn** [comment]
@maurii90 @Adrian62D I don't know if these existed before, but seems like BLDRS has some new github workflows and these are failing. Trying to debug it but the application freezes. It would be good to know what exactly we need from this fork - how is it meant to be different from the original bldrs repo - in order to know if we can get rid of some changes.

**Comment by Adrian62D** [comment]
The customizations covered hiding buttons that were not making sense in the context of vzyn. Hiding them probably causes the e2e test to fail.

**Comment by maurii90** [comment]
Yes, I didn't know they introduced cypress tests. So we need to fix/remove the test which makes no sense in our context. I'll do it in this sprint.

**Comment by maurii90** [comment]
Yes, I didn't know they introduced cypress tests. So we need to fix/remove the test which makes no sense in our context. I'll do it in this sprint.

**Pull request closed without merging**
